### ISSUE TITLE
withUpdate does not work with guest user

### ISSUE THREAD

**Issue by foobarbecue** [VulcanJS/Vulcan#2085] opened 2018-09-26 15:00 UTC
I have:

```
Users.groups.guests.can([
  'climbs.new',
  'climbs.update.all'
]);
```
and in the schema for the Climbs collection:
```
{ ...
  name: {
    label: 'Name',
    type: String,
    canRead: ['guests'],
    canCreate: ['guests'],
    canUpdate: ['guests'],
    optional: true,
  },
...
}
```
also:

`this.props.updateClimb({selector:{_id:climbId}, data:{'name': 'my climb'}});`

and when I'm not logged in (user is null), I get:

> Error: {"id":"app.operation_not_allowed","value":"check"}

If I log in, the update succeeds.

**Comment by Apollinaire** [comment] 2018-09-26 16:15
In your permissions, change `climbs.update.all` to `climb.update.all` (the s is gone) or `climbs.edit.all` (old version)
You should also change `climbs.new` to `climb.create`, it does the same but it's the most recent API.

**Comment by foobarbecue** [comment] 2018-09-27 04:00
I tried 'climb.update.all' and 'climb.update' and a few other things. I'm still getting the same error. I will work on a minimal case based on example-simple.

**Comment by eric-burel** [comment] 2018-09-27 07:14
Are you working on a recent version of Vulcan? I remember fixing smth like this very recently, you might not be up to date.

**Comment by foobarbecue** [comment] 2018-09-27 14:45
I have:

```
S:\active\climbshare-vulcan>meteor list
accounts-password  1.5.1  Password support for accounts
vulcan:admin       1.12.8  Vulcan components package
vulcan:core        1.12.8  Vulcan core package
vulcan:debug       1.12.8  Vulcan debug package
vulcan:i18n-en-us  1.12.8  Vulcan i18n package (en_US)
```

**Comment by SachaG** [comment] 2018-09-28 08:42
There might be a bug in Vulcan here but I do want to point out that writing `canUpdate: ['guests']` on a field means that any random person can load up your site and delete that field on any document in your db, they don't even have to log in. So I would usually avoid it.

**Comment by Apollinaire** [comment] 2018-09-28 08:45
Normally `climb.update.all` should work. Try using : `  mutations: getDefaultMutations({ collectionName: 'Climbs', typeName: 'Climb' }), `
@SachaG  I tried changing the permissions on the example-movies and `canUpdate : ['guests']` works

**Comment by foobarbecue** [comment] 2018-09-29 00:03
I agree that giving canUpdate to guests is a dangerous, atypical use case! I only wanted to do it during development because I was hoping to write the core mechanics of my app without worrying about accounts and auth, and add that part later.

I made a minimal case from example-simple here: https://github.com/foobarbecue/Vulcan-Starter/tree/mincase_for_vulcan_2085

It's a little bit complicated. If I simply changed permissions to allow guests all powers, then all the fields disappeared from the smartforms (presumably because `getEditableFields` et al decide what fields can be shown). So instead I made a thing where you click to create a new document and then double click to edit it, and this triggers the original issue I discussed above.

**Comment by ochicf** [comment] 2018-10-31 11:32
I think this issue is caused by the [check method in the default updateMutation](https://github.com/VulcanJS/Vulcan/blob/f162054a0b774c6f57fcf9e7d524cfb3c91de427/packages/vulcan-core/lib/modules/default_mutations.js#L86). It basically discards guests users before checking for permissions.

As a bypass, you can provide a default check callback for the mutation, like so:

```js
getDefaultMutations({
  typeName: '',
  options: {
    updateCheck: (user, document) => {
        // check if user owns the document being edited.
        // if they do, check if they can perform "foo.edit.own" action
        // if they don't, check if they can perform "foo.edit.all" action
        // OpenCRUD backwards compatibility
        return Users.owns(user, document)
          ? Users.canDo(user, [`${typeName.toLowerCase()}.update.own`, `${collectionName.toLowerCase()}.edit.own`])
          : Users.canDo(user, [`${typeName.toLowerCase()}.update.all`, `${collectionName.toLowerCase()}.edit.all`]);
    },
  },
});
```

**Comment by yannick-mayeur** [comment] 2019-12-17 14:19
In `default_mutations2.js` I feel like the guest users are not discarded. Could you check if this issue is still relevant to you @foobarbecue.

**Comment by eric-burel** [comment] 2019-12-17 16:57
Thanks for checking this, I am closing for now as group management has been approved.

**Closed by eric-burel** 2019-12-17 16:57 UTC
Labels: core, permissions
