### ISSUE TITLE
Accounts button disabled

### ISSUE THREAD

**Issue by eric-burel** [VulcanJS/Vulcan#1815] opened 2018-01-12 11:36 UTC
Hi,
The account buttons are disabled in production [(app here)](https://simply-charge-staging.herokuapp.com/), though they are working if I manually disable them in the React console.

It seems that the `Accounts.loginServicesConfigured()` events does not happen, so the buttons are never activated (waiting state [here](https://github.com/VulcanJS/Vulcan/blob/master/packages/vulcan-accounts/imports/ui/components/LoginForm.jsx#L101)).

I also have this empty collection in my DB:
`meteor_accounts_loginServiceConfiguration`

The bug appeared, of course, totally widly, the app use to work correctly.

Root URL seems correct too:
`ROOT_URL:        https://simply-charge-staging.herokuapp.com`

**Comment by luhagel** [comment] 2018-01-12 12:17
#1816 
Until the fix is deployed to Atmosphere etc, using a 2 repo approach to bundle the corrected version should do the trick

**Comment by eric-burel** [comment] 2018-01-12 14:09
Ok, just to note, underlying issue for people that encounter this is that `1.8.3` has (small) breaking changes, and versions are not locked by default.

I think it would be good to lock all versions by default (with vulcan:foobar@=1.8.x), since Vulcan user are used to go directly in the package list files anyway.

**Comment by SachaG** [comment] 2018-01-14 05:24
Just to clarify, is this a recent issue? Do you know when it was introduced, or what caused it?

**Comment by luhagel** [comment] 2018-01-14 18:36
Pretty sure it's also somehow related to the React 16 SSR changes, and it only appears in minified production builds.

**Comment by MHerszak** [comment] 2018-01-14 19:26
@luhagel can you clarify "related to ssr changes"? `Accounts.loginServicesConfigured()` is subscribing to `meteor.loginServiceConfiguration` and returns ready `true` when the subscription is ready. If ready, `waiting` turns false Is there a bottleneck I don't see?

**Comment by luhagel** [comment] 2018-01-15 11:51
Yeah, my suspicion is that there's a data mismatch between client and server, leading to one version overwriting the other with the incorrect `waiting` state

**Comment by MHerszak** [comment] 2018-01-15 15:52
Is someone working on this problem?

**Comment by MHerszak** [comment] 2018-01-16 23:46
@luhagel or @eric-burel what is the current workaround for this? As mentioned the production build is in a waiting state and I am trying to find the cause. Any ideas for a workaround?

**Comment by luhagel** [comment] 2018-01-17 10:38
@MHerszak bundle your local version with the build and replicate #1816

**Comment by MHerszak** [comment] 2018-01-17 14:39
@luhagel Which package versions are you using? The latest version?

**Comment by SachaG** [comment] 2018-01-20 02:09
I'm pushing 1.8.4 which includes this fix. Let me know if it helps.

**Comment by MHerszak** [comment] 2018-01-23 01:14
The issue seems is resolved. I am closing this for now.

**Comment by MHerszak** [comment] 2018-01-23 01:26
Nvm, state change isn't working anymore.

**Comment by Discordius** [comment] 2018-01-26 05:16
Does anyone have any potential fixes for this? I've been running into the state change issue.

**Comment by SachaG** [comment] 2018-01-26 10:20
In the meantime you can use different routes or handle the state changes yourself:

```js
import { Components, registerComponent } from 'meteor/vulcan:core';
import React, { PropTypes, Component } from 'react';
import { FormattedMessage } from 'meteor/vulcan:i18n';
import Dropdown from 'react-bootstrap/lib/Dropdown';
import { STATES } from 'meteor/vulcan:accounts';
import { Link } from 'react-router';

const UsersLogIn = ({state}) =>

  <div className="page accounts-page accounts-log-in">
    <Components.AccountsLoginForm showSignUpLink={false}/>
    <p className="accounts-prompt"><FormattedMessage id="accounts.dont_have_an_account"/> <Link to="/sign-up"><FormattedMessage id="accounts.sign_up_here"/></Link></p>
  </div>

UsersLogIn.displayName = 'UsersLogIn';

registerComponent('UsersLogIn', UsersLogIn);
```

```js
import { Components, registerComponent } from 'meteor/vulcan:core';
import React, { PropTypes, Component } from 'react';
import { FormattedMessage } from 'meteor/vulcan:i18n';
import { STATES } from 'meteor/vulcan:accounts';
import { Link } from 'react-router';

const UsersSignUp = ({state}) =>

  <div className="page accounts-page accounts-sign-up">
    <Components.AccountsLoginForm formState={STATES.SIGN_UP} showSignInLink={false}/>
    <p className="accounts-prompt"><FormattedMessage id="accounts.already_have_an_account"/> <Link to="/log-in"><FormattedMessage id="accounts.log_in_here"/></Link></p>
  </div>

UsersSignUp.displayName = 'UsersSignUp';

registerComponent('UsersSignUp', UsersSignUp);
```

**Comment by SachaG** [comment] 2018-01-26 10:45
I've opened an issue: https://github.com/facebook/react/issues/12102

**Comment by MHerszak** [comment] 2018-01-26 14:36
Yeah, I am handling this manually at the moment. Thanks for opening an issue, Sacha.

**Comment by SachaG** [comment] 2018-01-27 04:22
Here's a fix for now: https://github.com/VulcanJS/Vulcan/commit/6facf15e17fec0eff0804d35360579513e7f586f

**Comment by vincro** [comment] 2018-02-04 12:35
I had the same issue, which is now fixed by the update.

**Comment by nolandg** [comment] 2018-02-09 22:24
I'm seeing this issue where `setState` is having no persistent effect on `this.state` within `LoginFormInner` and a5c3785ed8d6a35868bc169f07e40e889087fd2e does not fix this.  **---Only in production mode :-( Works perfectly in dev**

My `input` component correctly calls [handleChange(field, evt)](https://github.com/VulcanJS/Vulcan/blob/7d03d8008e5937cf0b9e145e07d8278202547af5/packages/vulcan-accounts/imports/ui/components/LoginFormInner.jsx#L254) in `LoginFormInner` and that function calls `setState` with the correct values. Immediately after the `setState` call, `this.state` reflects the change but on the next call to `handleChange` the value is gone. As @SachaG said in his React issue, the callback for `setState` is never called in `handleChange`. The callback is called in dev but not production.

Any ideas? Can @SachaG explain why his above commit was supposed to fix this? Any guesses as to why it working **in dev but not production?**

Also, I'm noticing that my login form including the `AccountsButton`s are re-rendering on every `onChange` of  my text input (password and username etc) in dev but not in production. The whole form seems dead in production.

**Comment by nolandg** [comment] 2018-02-09 23:32
Ok. I think I figured it out. I say it's the fault of that `tracker-component` that `LoginFormInner` extends.

`tracker-component` was last updated 2 years ago. It's `setState` method relies on the undocumented private `this._reactInternalInstance` to decide how to update state. Which branch it takes in it's `setState` method changes based on whether you're in production or dev mode. I think the last 2 years of React updates have rendered this component obsolete and broken.

I have re-written the `setState` function of `tracker-component` to look like this:
````
  setState(state) {
    const newState = Object.assign({}, this.state, state);
    this.state = newState;
    return super.setState(newState);
  }
````
I removed the reliance on `_reactInternalInstance` and saved local state and called `super` for both cases. It's working for me in production and dev mode.

This is a small simple component. I propose we don't wait for a PR from it and simply include this component in vulcan-accounts. I could submit a PR for that next week if @SachaG agrees.

My login error messages stopped working though when I pulled that latest commit so I'll have to fix that too but I think that's unrelated and might be due to my implementation of `AccountsMessage`.

**Comment by SachaG** [comment] 2018-02-10 01:04
Oh nice! Yeah this would be a huge help, a PR would be great. Thanks for figuring this out, I've been struggling with this issue for a while…

**Comment by SachaG** [comment] 2018-02-18 05:12
@nolandg any update on this? would you have time to submit a PR?

**Comment by nolandg** [comment] 2018-02-18 06:23
Sorry for the delay. Let me know if there's any problems with it. I reset to a clean devel and it works fine for me in production mode.

**Closed** 2018-02-18 09:03 UTC
