### ISSUE TITLE
withDelete does not function

### ISSUE THREAD

**Issue by 143mailliw** [VulcanJS/Vulcan#2417] opened 2019-10-22 04:58 UTC
The function returned from withDelete does not work, with the error `[GraphQL error]: Message: Variable "$selector" got invalid value { selector: { documentId: [Object] } }; Field "selector" is not defined by type MovieSelectorUniqueInput., Location: line 1, col 22, Path: undefined`

The reproduction for this bug is available at https://github.com/143mailliw/Vulcan-withDelete-bug

**Comment by eric-burel** [comment] 2019-10-22 07:16
In `packages/vulcan-core/lib/modules/containers/delete.js` line 64 the function should take `{ selector }` as an argument instead of just `selector`, will try a fix and push it asap.

**Comment by eric-burel** [comment] 2019-10-22 08:18
Actually I am not sure of the expected behaviour and previous behaviour, I need to check that. In the current version you need to pass your selector directly (there is no other option anyway) instead of `{ selector: yourSelector}` but I can't tell if it's a breaking change or not.

**Comment by eric-burel** [comment] 2019-10-23 15:41
Fixed on devel now both syntaxes are ok, because API will change in next release anyway

**Closed** 2019-10-25 14:39 UTC
