### ISSUE TITLE
Resolver didn't return the new field in document of the component to edit a register

### ISSUE THREAD

**Issue by harold20** [VulcanJS/Vulcan#2277] opened 2019-04-16 23:56 UTC
Hello! I try to resolve the field of my schema to return a new field to use in the component, but it doesn't appear in the document of the component, only if I do the query on graphiql.

I do not know if I am doing something wrong or this is not posible. This is a part of my schema to save an id and resolve it as a link.
```
   imageId: {
     label: 'Image',
     type: String,
     optional: true,
     canRead: ['members', 'admins'],
     canCreate: ['members', 'admins'],
     canUpdate: ['members', 'admins'],
     control: 'Upload',
     resolveAs: {
       fieldName: 'imageUrl',
       type: 'String',
       resolver: async (s3images, args, {currentUser, Users}) => {
         if (!s3images.imageId) return null;
         const imageFile = await imagesFiles.loader.load(s3images.imageId);
         return imageFile ? imagesFiles.link(imageFile) : null;
       },
       addOriginalField: true
     },
   },
```

I expect that the resolver returns a new field called imageUrl in document in the component.

Any help is grateful :)

**Comment by SachaG** [comment] 2019-04-18 02:37
Does the fragment controlling the query include that `imageUrl` field?

**Comment by harold20** [comment] 2019-04-22 16:33
Hi thank for answering me and sorry for the delay.

Yes, @SachaG  this is my fragment

`registerFragment(`
  fragment PicsFragment on Pic {
    _id
    createdAt
    userId
    imageId
    imageUrl
    body
  }
`);`

And here the way I send it to the datatable
`    <Components.Datatable
        collection={Pics}
        columns={['_id', 'imageId', 'body', 'imageUrl']}
        emptyState={<p className="datatable-empty">No images to display</p>}
        options={{
            fragmentName: 'PicsFragment',
            limit: 20
        }}
    />`

**Comment by SachaG** [comment] 2019-04-30 06:34
You can use your devtool's network tab to inspect the exact request being generated and sent to the server, as well as the data being returned. That should help narrow down the issue.

**Comment by ShaLi2204** [comment] 2019-06-07 06:35
Hi there, 

did you manage to solve this problem? I have a similar issue:
I define a field too with resolveAs. The field can be accessed from GraphQL, values also look fine. But I cannot access them from front page. 
How did you solve this problem? I would really appreciate your help!

**Comment by eric-burel** [comment] 2019-09-04 13:14
Hi, for such issues checking your DevTools Network tab, on the /graphql endpoint, is the way to go as stated previously by Sacha. We can help to debug but we need more info about what query is sent to the server and what is returned in a page that does'n't work as expected.

**Comment by eric-burel** [comment] 2019-12-11 13:42
Closing due to lack of infos to reproduce but feel free to open an issue if it happens again

**Closed by eric-burel** 2019-12-11 13:42 UTC
