### ISSUE TITLE
Duplicate Item with withMulti 

### ISSUE THREAD

**Issue by IBRAHIMDANS** [VulcanJS/Vulcan#2719] opened 2021-06-04 10:04 UTC
**Describe the bug**
Hola, 
I have a problem with withMulti2 when I make a request by limiting.
I have data which is duplicated in result
node  v14.16.1
vulcan 

To Reproduce

1 -  withMulti2(
...
  limit: 3)([component])

2 - in my component call loadMoreInc() after `result` content duplicated item

**Comment by eric-burel** [comment] 2021-06-04 14:40
According to the code from your PR, this is a backend issue => the multi resolver is sending the same item twice, as if the limit was taken into account incorectly

**Comment by GraemeFulton** [comment] 2021-06-17 12:10
`useMulti2` in meteor seems to work for me, but useMulti from vulcanjs/hooks is not getting the filter after loadmore. 

I am filtering documents by `userId`, and I can see that in the first query (before loadmore), all userId input is present:

<img width="812" alt="Screenshot 2021-06-17 at 13 08 35" src="https://user-images.githubusercontent.com/4354786/122393809-2ee3d480-cf6d-11eb-8745-c653ecc1b5d6.png">

After loadMore button clicked, the query no longer has those inputs:

<img width="559" alt="Screenshot 2021-06-17 at 13 05 53" src="https://user-images.githubusercontent.com/4354786/122393448-cdbc0100-cf6c-11eb-9d23-627faa40521d.png">

So I'm just looking into that now 🤓

**Comment by eric-burel** [comment] 2021-06-18 15:48
@GraemeFulton will be fixed by https://github.com/VulcanJS/vulcan-npm/pull/56/files

@IBRAHIMDANS the issue is that variables are not correclty merged in the hook, so in the loadMore/loadMoreInc calls, it indeed loses the filter. Instead of using "uniq", the solution is to fix the variable merging pattern, you can take a look at the PR: https://github.com/VulcanJS/vulcan-npm/pull/56/files

To fix this:
- I get current variables from the queryResult (when doing `useQuery`, Apollo returns the result but also the variables you used to get this result)
- I merge the variables (previously, I was just merging the pagination inputs)

**Closed** 2023-08-28 09:41 UTC
Labels: next release
